FROM golang:1.25-alpine AS builder

WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bucket-api ./cmd

# Final minimal image
FROM alpine:latest
WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/bucket-api .
# Copy .env file if available (or use environment variables)
COPY .env* ./

EXPOSE 3000
CMD ["./bucket-api"]
